/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kchua' at '6/09/17 11:56 AM' with Gradle 3.2
 *
 * @author kchua, @date 6/09/17 11:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
